spring:
   application:
      name: search_application
   datasource: 
      driverClassName: com.mysql.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/search_app?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata&autoreconnect=true"
      password: "root123"
      username: "root"
   jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        dialect :  org.hibernate.dialect.MySQL5InnoDBDialect
        default_schema: mydb
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true